baseURL: "https://articles.panelista.com/"
languageCode: "en-us"
title: "Panelista Articles"
pygmentsstyle: "monokai"

markup:
  goldmark:
    renderer:
      unsafe: true

# Theme settings
theme: novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
