baseURL: "https://articles.panelista.com/"
title: "Panelista Articles"
pygmentsstyle: "monokai"

markup:
  goldmark:
    renderer:
      unsafe: true

# Theme settings
theme: novela
paginate: 24
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
