baseURL: "https://panelista.com/articles/"
languageCode: "en-us"
title: "Panelista Articles"
pygmentsstyle: "monokai"

# Theme settings
theme: novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
